name: Release
on:
  push:
    tags:
      - release/[0-9]+.[0-9]+.[0-9]+
jobs:
  edit-ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          YA_TOKEN: ${{ secrets.YA_TOKEN }}
          COMPANY_ID: ${{ secrets.COMPANY_ID }}
        run: |
          chmod +x .github/workflows/scripts/edit_ticket.sh
          .github/workflows/scripts/edit_ticket.sh
