name: Release
on:
  push:
    tags: release/\d+.\d+.\d+
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm run ci
      - run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
          node-version: '16.16.0'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build