name: Release
on:
  push:
    tags:
      - release/[0-9]+.[0-9]+.[0-9]+
jobs:
  edit-ticket:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          YA_TOKEN: ${{ secrets.YA_TOKEN }}
          COMPANY_ID: ${{ secrets.COMPANY_ID }}
          TICKET_TEXT: "НОВЫЙ ЗАГОЛОВОК"
        run: |
          chmod +x scripts/edit_ticket.sh
          scripts/edit_ticket.sh >> $EXIT_STATUS
          echo "Exit status= $EXIT_STATUS "
